### ISSUE TITLE
Closing a browser tab and re-opening results in a blank iframe

### ISSUE THREAD

**Issue by westonruter** [xwp/wordpress-develop#166]
So if you open the customizer, make a change (so that you'll see the UUID added in the URL via replaceState) and then close the tab. If you reopen the tab it should restore the changes you were last working on since they are saved in the changeset. It seems to not be working as expected. For one it seems that Chrome caches not the most latest JS state, but then also the iframe is blank even though it has a `src` set. Any ideas?

**Comment by westonruter** [comment]
I thought maybe the browser's bfcache (back-froward cache) could be causing problems, so I tried:

```js
$( window ).on( 'unload', function(){} );
$( window ).on( 'beforeunload', function(){} );
```

But it didn't seem to help.

I also tried setting the `src` on the `iframe` _after_ it was embedded into the DOM, but that didn't help either at https://github.com/xwp/wordpress-develop/blob/1764f1b2945e5777efd1faf8ec2034ba2aeac395/src/wp-admin/js/customize-controls.js#L3289

But that didn't help either.

**Comment by westonruter** [comment]
The issue also happens when leaving the customizer and then hitting the browser's back button to go back into the customizer. Probably the same mechanism is being used in Chrome for restoring a tab as using the back button.

Note that if you do a full reload of the window after restoring the tab, then the iframe and changeset content are fully restored.

**Comment by mehigh** [comment]
I didn't have time to look into this today, but tomorrow I should have more time available.

**Comment by mehigh** [comment]
I've set this up under a new Kalabox WP instance and tested the code inside the trac-30937 branch. In short -> under Kalabox there are no issues whatsoever.

At first, I've tested this in all browsers inside of the trac-30937 branch. This is the outcome.

Safari 9.0.3 (El Capitan): 
made changes (changed title/motto/added a menu)
closed the tab + reopened it made all of my changes visible ( http://dsh.re/1b084 )

Chrome 53.0.2785.143: 
made changes (changed title/setup static page for homepage), 
closed the tab + closed the tab + reopened it made all of my changes visible ( http://dsh.re/e9f85 )

Chrome 54.0.2840.59
made changes (removed a lot of widgets, added 2 meta widgets)
closed the tab + closed the tab + reopened it made all of my changes visible ( http://dsh.re/2d9a4 )

Chrome Beta 56.0.2889.0 canary 
made changes (renamed titles of all widgets, title)
closed the tab + closed the tab + reopened it made all of my changes visible ( http://dsh.re/ac581 )

Firefox Developer Edition 51.0a2 
made changes (replaced all widgets by a text widget)
closed the tab + closed the tab + reopened it made all of my changes visible ( http://dsh.re/d6028 )

Vivaldi 1.4.589
made changes (added body background)
closed the tab + closed the tab + reopened it made all of my changes visible ( http://dsh.re/20ace )

Blisk 0.61.2743.16
made changes (added header image)
closed the tab + closed the tab + reopened it made all of my changes visible ( http://dsh.re/f857c )
This one has 2 windows showing up at once (something specific to this browser to speed up responsive development)

All screenshots have been made after closing the tab and opening again (using command+shift+t or command+z).

I'm going to test this out next on a different environment next just in the latest stable Chrome browser to see if I can replicate it.

**Comment by mehigh** [comment]
I've deployed this to a live server (nginx/mysql/php 5.6) and tested this with a backup of a test site's data (but without the theme / plugins) and the closing of the chrome tab + reopening it ... or simply loading the page by itself multiple times confirmed this to be functioning correctly ( http://dsh.re/089db ).

Since this can't be replicated, I'm thinking that maybe one extension in the browser you tested this in might've caused it? Or maybe the debug settings on the development box could be the blame here?

**Comment by mehigh** [comment]
When activating the plug-in *customize-posts* the functionality glitch appears. 

Neither of the following plugins are causing issues:
* customize-inline-editing
* customize-nav-menu-item-custom-fields
* customize-object-selector
* customizer-browser-history
* customizer-dev-tools
* customize-validate-entitled-settings
* js-widgets
* rest-api

Having all of them present or not does not influence the bug introduced by *customize-posts* plug-in.

**Comment by westonruter** [comment]
Thanks for looking into that!

**Comment by mehigh** [comment]
I'm trying to see what thing inside customize-posts might be triggering this. As I get to a minimal reproducible scenario I'll update the ticket.

**Comment by mehigh** [comment]
At first I was thinking that maybe some of the JS in the customize-posts plug-in might've been the culprit for this one... but even after removing all of the JS enqueues the bug continued to persist: refreshing the page loads things perfectly, as when closing the tab and reopening it causes the empty iframe. 
So it might be something in the .php specifically here causing the hick-up. 

I'm looking into seeing whether dropping bits of the PHP code can also make the bug disappear, at least that will point us into what specific functionality is to blame.

**Comment by mehigh** [comment]
I started chewing stuff of from:
inside *class-wp-customize-posts.php*

And when I comment out the following:
```php
add_action( 'customize_controls_print_footer_scripts', array( $this, 'render_templates' ) );
```
the bug stops from occurring.

So I've went ahead and created a minimal scenario for the bug, and that consists of just 3 actions activated, like in the following 3 actions active: customize_controls_enqueue_scripts, customize_controls_init and customize_controls_print_footer_scripts. When all these 3 are active and all the rest are inactive, the bug occurs in Chrome.

How my minimal test-case scenario code looks like (with all of the JS files removed - so they are out of discussion with regards to having something to do with reproducing the bug):
```php
		add_action( 'customize_controls_enqueue_scripts', array( $this, 'enqueue_scripts' ) );
		add_action( 'customize_controls_init', array( $this, 'enqueue_editor' ) );

		# add_filter( 'customize_refresh_nonces', array( $this, 'add_customize_nonce' ) );
		# add_action( 'customize_register', array( $this, 'ensure_static_front_page_constructs_registered' ), 11 );
		# add_action( 'customize_register', array( $this, 'register_constructs' ), 20 );
		# add_action( 'init', array( $this, 'register_meta' ), 100 );
		# add_filter( 'customize_dynamic_setting_args', array( $this, 'filter_customize_dynamic_setting_args' ), 10, 2 );
		# add_filter( 'customize_dynamic_setting_class', array( $this, 'filter_customize_dynamic_setting_class' ), 5, 3 );
		# add_filter( 'customize_save_response', array( $this, 'filter_customize_save_response_for_conflicts' ), 10, 2 );

		# add_filter( 'customize_save_response', array( $this, 'filter_customize_save_response_to_export_saved_values' ), 10, 2 );
		add_action( 'customize_controls_print_footer_scripts', array( $this, 'render_templates' ) );
		# add_filter( 'customize_snapshot_save', array( $this, 'transition_customize_draft' ) );
		# add_action( 'after_setup_theme', array( $this, 'preview_customize_draft_post_ids' ) );
		# add_action( 'pre_get_posts', array( $this, 'preview_customize_draft' ) );
		# add_filter( 'post_link', array( $this, 'post_link_draft' ), 10, 2 );
		# add_filter( 'post_type_link', array( $this, 'post_link_draft' ), 10, 2 );
		# add_filter( 'page_link', array( $this, 'post_link_draft' ), 10, 2 );
		# or bug above

		# add_action( 'wp_ajax_customize-posts-insert-auto-draft', array( $this, 'ajax_insert_auto_draft_post' ) );
		# add_action( 'wp_ajax_customize-posts-fetch-settings', array( $this, 'ajax_fetch_settings' ) );
		# add_action( 'wp_ajax_customize-posts-select2-query', array( $this, 'ajax_posts_select2_query' ) );
		# add_action( 'customize_register', array( $this, 'replace_nav_menus_ajax_handlers' ) );
```

**Comment by mehigh** [comment]
As I dived even deeper I discovered that commenting out just the following from inside `public function render_editor() {` makes the bug go away:
```php
			// The settings passed in here are derived from those used in edit-form-advanced.php.
			wp_editor( '', 'customize-posts-content', array(
				'_content_editor_dfw' => false,
				'drag_drop_upload' => true,
				'tabfocus_elements' => 'content-html,save-post',
				'editor_height' => 200,
				'default_editor' => 'tinymce',
				'tinymce' => array(
					'resize' => false,
					'wp_autoresize_on' => false,
					'add_unload_trigger' => false,
				),
			) );
```

**Comment by mehigh** [comment]
This is an odd-ball and seems to connect more to a tinyMce bug rather than something introduced by either customize-posts or this new functionality. Not sure if it's worth pursuing further.

**Comment by westonruter** [comment]
Awesome. @mehigh EXTREMELY helpful!!! You are a gentleman and a scholar.
