### ISSUE TITLE
Changesets: Subdirectory path appended to preview iframe

### ISSUE THREAD

**Issue by dlh01** [xwp/wordpress-develop#177]
As discussed at https://wordpress.slack.com/archives/core-customize/p1476759582002552, re. #161: I have an install at `example.com/src/`, and when a full-page refresh occurs, the subdirectory is appended to the preview iframe -- `/src/src/`, `/src/src/src/`, etc. 

I'll investigate, but if anyone else can see where the issue might be more quickly, please chime in.

**Comment by westonruter** [comment]
Cheers! Fixed inhttps://github.com/xwp/wordpress-develop/pull/161/commits/001f3d39cc16e7b13c450a2f6062cf824e6b6e3a
