### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by nandotess** [xwp/wordpress-develop#178]
Guys, I'm receiving this message in my console when I try to test the latest master merge (Customize: Introduce custom CSS for extending theme styles):

`customize-base.js?ver=4.7-alpha-38178-src:753`

`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://tests.mamp') does not match the recipient window's origin ('http://tests.mamp:8888').`

As you can see, I'm running a localhost with a specific port. I can change the port for this test if this issue happens only for me.

I downloaded from the master branch few minutes ago, after the merge from "Customize: Introduce custom CSS for extending theme styles" branch.

`git clone https://github.com/xwp/wordpress-develop.git`

Thank you! And sorry if this issue is not appropriated here, in this repo.

Screenshot:
![screen shot 2016-10-19 at 16 36 36](https://cloud.githubusercontent.com/assets/804109/19532402/4e85c604-961a-11e6-9cb4-e70082e80c25.png)

**Comment by westonruter** [comment]
@nandotess would you please open the ticket on Trac instead? I do not think the issue you're describing is related to Custom CSS but rather is a defect in changesets.

**Comment by westonruter** [comment]
I suspect that the port number is getting dropped erroneously.

**Comment by nandotess** [comment]
Thank you @westonruter. Ticked opened on Trac.
